services:
  postgres:
    environment:
      POSTGRES_DB: userdb_test

  app:
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/userdb_test
    command: >
      sh -c "pytest tests/ -v"
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
